function varargout = reportError(ME)
%REPORTERROR Display, or return, report of error to command-line in error color (i.e. red), without throwing error
%% SYNTAX
%   function reportError(ME)
%   function errString = reportError(ME)%
%       errString: 'Safe' error report string, suited for use in fprintf statements by caller
%
%% NOTES
%   Generally suited as a safe-in-all-cases display of the string generated by the MException getReport() method
%   Particularly suited for:
%       Use in callback functions which cannot generate true exceptions
%       Error messages/reports that contan filenames/paths which can confuse frintf
%

errString = ME.getReport('extended','hyperlinks','off');
errString = strrep(errString,'\','\\'); %Don't recognize any escape characters
errString = strrep(errString,'%','%%'); %Don't recognize any formatting characters

if nargout
    varargout = {errString};
else
    fprintf(2,errString);
    fprintf(1,'\n');
end

end



%--------------------------------------------------------------------------%
% reportError.m                                                            %
% Copyright © 2015 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage 5 is licensed under the Apache License, Version 2.0            %
% (the "License"); you may not use any files contained within the          %
% ScanImage 5 release  except in compliance with the License.              %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
